eUseControl/eUseControl.Web/Controllers/UserRegistrationController.cs
using Domain.Entities.User;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.BusinessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Authentication;
using System.Web;
using System.Web.Mvc;

namespace eUseControl.Web.Controllers
{
    public class UserRegistrationController : LoginController
    {
        private readonly ISession _session;

        public UserRegistrationController()
        {
            var bl = new BussinesLogic();
            _session = bl.GetSessionBL();
        }

        public ActionResult RegisterPage()
        {
            // Verifică utilizatorul după Token, dacă este autorizat
            var authToken = Request.Cookies["X-KEY"]?.Value;
            if (authToken != null && GetUserDetails(authToken) != null)
            {
                TempData["ErrorMessage"] = "[!] Sunteți deja logat.";
                return RedirectToAction("HomePage", "Home");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterUser(URegisterData register)
        {
            if (ModelState.IsValid)
            {
                URegisterData data = new URegisterData
                {
                    Nume = register.Nume,
                    Prenume = register.Prenume,
                    Email = register.Email,
                    Password = register.Password
                };

                var userRegister = _session.UserRegister(data);
                if (userRegister == null)
                {
                    throw new AuthenticationException("ERROR. No registration response!");
                }

                if (userRegister.Status)
                {
                    return RedirectToAction("LogIn", "Login");
                }
                else
                {
                    ModelState.AddModelError("", userRegister.StatusMsg);
                    return View("RegisterPage", register);
                }
            }

            return RedirectToAction("HomePage", "Home");
        }
    }
}

eUseControl/eUseControl.Web/Views/UserRegistration/RegisterPage.cshtml
@{
    ViewBag.Title = "RegisterPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Web.Optimization
@model eUseControl.Web.Models.UserRegister

<main>
    <section class="register-section">
        <div class="register-container">
            @using (Html.BeginForm("RegisterUser", "UserRegistration", FormMethod.Post, new { id = "registerForm" }))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <label for="Nume">Nume</label>
                    <input type="text" id="Nume" name="Nume" required minlength="5" maxlength="20" />
                    <span class="text-danger" id="numeError"></span>
                </div>
                <div class="form-group">
                    <label for="Prenume">Prenume</label>
                    <input type="text" id="Prenume" name="Prenume" required minlength="5" maxlength="20" />
                    <span class="text-danger" id="prenumeError"></span>
                </div>
                <div class="form-group">
                    <label for="Email">Email</label>
                    <input type="email" id="Email" name="Email" required minlength="10" maxlength="30" />
                    <span class="text-danger" id="emailError"></span>
                </div>
                <div class="form-group">
                    <label for="Password">Password</label>
                    <input type="password" id="Password" name="Password" required minlength="8" maxlength="30" />
                    <span class="text-danger" id="passwordError"></span>
                </div>
                <div class="form-group submit-container">
                    <button type="submit">Register</button>
                </div>
            }
        </div>
    </section>
</main>

<script>
    document.getElementById('registerForm').addEventListener('submit', function (event) {
        var isValid = true;

        // Clear error mesages
        document.getElementById('numeError').textContent = '';
        document.getElementById('prenumeError').textContent = '';
        document.getElementById('emailError').textContent = '';
        document.getElementById('passwordError').textContent = '';

        var nume = document.getElementById('Nume').value;
        if (nume.length < 5 || nume.length > 20) {
            isValid = false;
            document.getElementById('numeError').textContent = 'Nume trebuie să aibă între 5 și 20 caractere.';
        }

        var prenume = document.getElementById('Prenume').value;
        if (prenume.length < 5 || prenume.length > 20) {
            isValid = false;
            document.getElementById('prenumeError').textContent = 'Prenume trebuie să aibă între 5 și 20 caractere.';
        }

        var email = document.getElementById('Email').value;
        if (email.length < 10 || email.length > 30) {
            isValid = false;
            document.getElementById('emailError').textContent = 'Email trebuie să aibă între 10 și 30 caractere.';
        }

        var password = document.getElementById('Password').value;
        if (password.length < 8 || password.length > 30) {
            isValid = false;
            document.getElementById('passwordError').textContent = 'Password trebuie să aibă între 8 și 30 caractere.';
        }

        // Prevent
        if (!isValid) {
            event.preventDefault();
        }
    });
</script>