eUseControl/eUseControl.Web/Controllers/AdminController.cs
using eUseControl.BusinessLogic.DBModel;
using eUseControl.Domain.Entities.Orders;
using eUseControl.Domain.Entities.User;
using eUseControl.Web.Attribute;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace eUseControl.Web.Controllers
{
     [AdminMod]
     public class AdminController : Controller
     {
          private readonly OrderContext _db = new OrderContext();
          private readonly UserContext _user = new UserContext();

          // Users Management
          public ActionResult Users()
          {
               var users = _user.Users.ToList();
               return View(users);
          }

          public ActionResult CreateUser()
          {
               return View();
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult CreateUser(UDbTable user)
          {
               if (ModelState.IsValid)
               {
                    _user.Users.Add(user);
                    _user.SaveChanges();
                    return RedirectToAction("Users");
               }
               return View(user);
          }

          public ActionResult EditUser(int? id)
          {
               if (id == null)
               {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
               }

               UDbTable user = _user.Users.Find(id);
               if (user == null)
               {
                    return HttpNotFound();
               }

               return View(user);
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult EditUser(UDbTable user)
          {
               if (ModelState.IsValid)
               {
                    _user.Entry(user).State = EntityState.Modified;
                    _user.SaveChanges();
                    return RedirectToAction("Users");
               }
               return View(user);
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult DeleteUser(int id)
          {
               UDbTable user = _user.Users.Find(id);
               if (user != null)
               {
                    _user.Users.Remove(user);
                    _user.SaveChanges();
               }
               return RedirectToAction("Users");
          }

          // Products Management
          public ActionResult Products()
          {
               var products = _db.Products.ToList();
               return View(products);
          }

          public ActionResult Create()
          {
               return View();
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult Create(Product product)
          {
               if (ModelState.IsValid)
               {
                    _db.Products.Add(product);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
               }
               return View(product);
          }

          public ActionResult Edit(int? id)
          {
               if (id == null)
               {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
               }

               Product product = _db.Products.Find(id);
               if (product == null)
               {
                    return HttpNotFound();
               }
               return View(product);
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult Edit(Product product)
          {
               if (ModelState.IsValid)
               {
                    _db.Entry(product).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
               }
               return View(product);
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult Delete(int id)
          {
               Product product = _db.Products.Find(id);
               if (product != null)
               {
                    _db.Products.Remove(product);
                    _db.SaveChanges();
               }
               return RedirectToAction("Index");
          }

          // Orders Management
          public ActionResult Orders()
          {
               var orders = _db.Orders.Include(o => o.OrderDetails.Select(od => od.Product)).ToList();
               return View(orders);
          }

          protected override void Dispose(bool disposing)
          {
               if (disposing)
               {
                    _db.Dispose();
                    _user.Dispose();
               }
               base.Dispose(disposing);
          }
     }
}

eUseControl/eUseControl.Web/Controllers/MyOrderController.cs
using System.Linq;
using System.Web.Mvc;
using eUseControl.Domain.Entities.Orders;
using System.Data.Entity;
using eUseControl.BusinessLogic.DBModel;
using eUseControl.Web.Attribute;

namespace eUseControl.Web.Controllers
{
    [UserMod]
    public class MyOrderController : Controller
    {
        private readonly OrderContext _db = new OrderContext();

        public ActionResult MyOrders()
        {
            var userEmail = GetCurrentUserEmail();

            var orders = _db.Orders
              .Include(o => o.OrderDetails.Select(od => od.Product))
              .Where(o => o.UserId == userEmail)
              .ToList();
            return View(orders);
        }

        private string GetCurrentUserEmail()
        {
            var authCookie = Request.Cookies["X-KEY"];
            if (authCookie != null)
            {
                string authToken = authCookie.Value;
                var currentUser = new LoginController().GetUserDetails(authToken);
                if (currentUser != null)
                {
                    return currentUser.Email;
                }
            }
            return null;
        }
    }
}

eUseControl/eUseControl.Web/Controllers/OrderController.cs
using Domain.Entities.Orders;
using eUseControl.BusinessLogic.DBModel;
using eUseControl.Domain.Entities.Orders;
using eUseControl.Web.Attribute;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eUseControl.Web.Controllers
{
     [UserMod]
    public class OrderController : LoginController
    {
        private readonly OrderContext _context;

        public OrderController()
        {
            _context = new OrderContext();
        }

        public ActionResult Index()
        {
            var cart = GetCartItems();
            return View(cart);
        }

        public ActionResult AddToCart(int productId)
        {
            var product = _context.Products.Find(productId);
            if (product == null)
            {
                return HttpNotFound();
            }
            string cartId = GetCartId();

            var cartItem = _context.CartItems.SingleOrDefault(c => c.Product.ProductId == productId && c.CartId == cartId);

            if (cartItem == null)
            {
                cartItem = new CartItem
                {
                    Product = product,
                    Quantity = 1,
                    CartId = GetCartId()
                };
                _context.CartItems.Add(cartItem);
            }
            else
            {
                cartItem.Quantity++;
            }

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Buy()
        {
            var authToken = Request.Cookies["X-KEY"]?.Value;

            var currentUser = GetUserDetails(authToken);
            if (currentUser == null)
            {
                TempData["ErrorMessage"] = "[!] Nu s-a putut obține detaliile utilizatorului.";
                return RedirectToAction("HomePage", "Home");
            }

            var cartItems = GetCartItems();
            if (!cartItems.Any())
            {
                return RedirectToAction("Index");
            }

            var order = new Order
            {
                UserId = currentUser.Email,
                OrderDate = DateTime.Now,
                OrderDetails = cartItems.Select(c => new OrderDetail
                {
                    ProductId = c.Product.ProductId,
                    Quantity = c.Quantity,
                    UnitPrice = c.Product.Price
                }).ToList()
            };

            _context.Orders.Add(order);
            _context.CartItems.RemoveRange(cartItems);
            _context.SaveChanges();

            return RedirectToAction("ThankYou");
        }

        public ActionResult ThankYou()
        {
            return View();
        }

        private string GetCartId()
        {
            if (Session["CartId"] == null)
            {
                Session["CartId"] = Guid.NewGuid().ToString();
            }
            return Session["CartId"].ToString();
        }

        private List<CartItem> GetCartItems()
        {
            var cartId = GetCartId();
            return _context.CartItems.Where(c => c.CartId == cartId).Include(c => c.Product).ToList();
        }

        public ActionResult RemoveFromCart(int productId)
        {
            var authToken = Request.Cookies["X-KEY"]?.Value;
            if (authToken == null)
            {
                TempData["ErrorMessage"] = "[!] Nu sunteți logat pentru a șterge produsul din coș.";
                return RedirectToAction("HomePage", "Home");
            }

            string cartId = GetCartId();
            var cartItem = _context.CartItems.SingleOrDefault(c => c.Product.ProductId == productId && c.CartId == cartId);

            if (cartItem != null)
            {
                _context.CartItems.Remove(cartItem);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult UserAddress()
        {
          return View();
        }

        public ActionResult BuyPhysicalCopy(Order address)
         {
               var authToken = Request.Cookies["X-KEY"]?.Value;

               var currentUser = GetUserDetails(authToken);
               if (currentUser == null)
               {
                    TempData["ErrorMessage"] = "[!] Nu s-a putut obține detaliile utilizatorului.";
                    return RedirectToAction("HomePage", "Home");
               }

               var cartItems = GetCartItems();
               if (!cartItems.Any())
               {
                    return RedirectToAction("Index");
               }

               var order = new Order
               {
                    UserId = currentUser.Email,
                    OrderDate = DateTime.Now,
                    UserAddress = address.UserAddress,
                    UserIndex = address.UserIndex,
                    UserPhoneNumber = address.UserPhoneNumber,
                    OrderDetails = cartItems.Select(c => new OrderDetail
                    {
                         ProductId = c.Product.ProductId,
                         Quantity = c.Quantity,
                         UnitPrice = c.Product.Price
                    }).ToList()
                   
               };

               _context.Orders.Add(order);
               _context.CartItems.RemoveRange(cartItems);
               _context.SaveChanges();

               return RedirectToAction("ThankYou");
         }
    }
}

eUseControl/eUseControl.Web/Controllers/SearchBarController.cs
using eUseControl.BusinessLogic.DBModel;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.BusinessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eUseControl.Domain.Entities.Orders;

namespace eUseControl.Web.Controllers
{
    public class SearchBarController : Controller
    {
          private readonly ISession _session;
          private readonly OrderContext _context;

          public SearchBarController()
        {
             var bl = new BussinesLogic();
             _session = bl.GetSessionBL();
             _context = new OrderContext();
        }
          public ActionResult Search(string query)
          {
               if (string.IsNullOrEmpty(query))
               {
                    return View("SearchResults", new List<Product>());
               }

               var products = _context.Products
                                      .Where(p => p.Name.Contains(query))
                                      .ToList();

               return View("SearchResults", products);
          }

     }
}

eUseControl/eUseControl.Web/Views/Shared/_Footer.cshtml
<!-- Begin Footer Area -->
<div class="footer">
    <!-- Begin Footer Static Top Area -->
    <div class="footer-static-top">
        <div class="container">
            <!-- Begin Footer Shipping Area -->
            <div class="footer-shipping pt-60 pb-25">
                <div class="row">
                    <!-- Safe payment -->
                    <div class="col-lg-3 col-md-6 col-sm-6 pb-sm-55 pb-xs-55">
                        <div class="li-shipping-inner-box">
                            <div class="shipping-icon">
                                <img src="~/Content/images/shipping-icon/2.png" alt="Shipping Icon">
                            </div>
                            <div class="shipping-text">
                                <h2>Plată sigură</h2>
                            </div>
                        </div>
                    </div>
                    <!-- Shop with confidence -->
                    <div class="col-lg-3 col-md-6 col-sm-6 pb-xs-30">
                        <div class="li-shipping-inner-box">
                            <div class="shipping-icon">
                                <img src="~/Content/images/shipping-icon/3.png" alt="Shipping Icon">
                            </div>
                            <div class="shipping-text">
                                <h2>Cumpără cu încredere</h2>
                            </div>
                        </div>
                    </div>
                    <!-- Best prices-->
                    <div class="col-lg-3 col-md-6 col-sm-6 pb-xs-30">
                        <div class="li-shipping-inner-box">
                            <div class="shipping-icon">
                                <img src="~/Content/images/shipping-icon/4.png" alt="Shipping Icon">
                            </div>
                            <div class="shipping-text">
                                <h2>Cele mai bune prețuri</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer Shipping Area End Here -->
        </div>
    </div>
    <!-- Footer Static Top Area End Here -->
    <!-- Begin Footer Static Middle Area -->
    <div class="footer-static-middle">
        <div class="container">
            <div class="footer-logo-wrap pt-50 pb-35">
                <div class="row">
                    <!-- Begin Footer Logo Area -->
                    <div class="col-lg-4 col-md-6">
                        <div class="footer-logo">
                            <img src="~/Content/images/menu/logo/1.png" alt="Footer Logo">
                            <p class="info">
                                Cel mai bun magazin pentru achiziționarea jocurilor video.
                            </p>
                        </div>
                        <ul class="des">
                            <li>
                                <span>Address: </span>
                                Moldova, Chisinau, st. Bolgarskaya 9, of. 5
                            </li>
                            <li>
                                <span>Phone: </span>
                                (+373) 11 22 33 44
                            </li>
                            <li>
                                <span>Email: </span>
                                easyplay.md@gmail.com
                            </li>
                        </ul>
                    </div>
                    <!-- Footer Logo Area End Here -->
                    <!-- Begin Footer Block Area 
                    <div class="col-lg-2 col-md-3 col-sm-6">
                        <div class="footer-block">
                            <h3 class="footer-block-title">Our company</h3>
                            <ul>
                                <li><a href="#">Livrarea</a></li>
                                <li><a href="#">Contacte</a></li>

                            </ul>
                        </div>
                    </div> -->
                    <!-- Footer Block Area End Here -->
                    <!-- Begin Footer Block Area -->
                    <div class="col-lg-4">
                        <div class="footer-block">
                            <h3 class="footer-block-title">Follow Us</h3>
                            <ul class="social-link">
                                <li class="twitter">
                                    <a href="https://twitter.com/" data-toggle="tooltip" target="_blank" title="Twitter">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li class="facebook">
                                    <a href="https://www.facebook.com/" data-toggle="tooltip" target="_blank" title="Facebook">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li class="youtube">
                                    <a href="https://www.youtube.com/" data-toggle="tooltip" target="_blank" title="Youtube">
                                        <i class="fa fa-youtube"></i>
                                    </a>
                                </li>
                                <li class="instagram">
                                    <a href="https://www.instagram.com/" data-toggle="tooltip" target="_blank" title="Instagram">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Footer Block Area End Here -->
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Static Middle Area End Here -->
</div>
<!-- Footer Area End Here -->

eUseControl/eUseControl.Web/Views/Shared/_Header.cshtml
@model dynamic

<!-- Begin Body Wrapper -->
<div class="body-wrapper">
    <!-- Begin Header Area -->
    <header class="li-header-4">
        <!-- Begin Header Top Area -->
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <!-- Begin Header Top Left Area -->
                    <div class="col-lg-3 col-md-4">
                        <div class="header-top-left">
                            <ul class="phone-wrap">
                                <li><span>Nr. de contact: (+373) 11 22 33 44</span></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Header Top Left Area End Here -->
                    <!-- Begin Header Top Right Area -->
                    <div class="col-lg-9 col-md-8">
                        <div class="header-top-right">
                             <ul class="ht-menu">
                                  <!-- Begin Setting Area -->
                                  <li><a href="@Url.Action("Products", "Admin")">Admin Products</a></li>
                                  <li><a href="@Url.Action("Users", "Admin")">Admin Users</a></li>
                                  <li><a href="@Url.Action("Orders", "Admin")">Admin Orders</a></li>
                                  <li><a href="@Url.Action("LogIn", "Login")">Logare</a></li>
                                  <li><a href="@Url.Action("RegisterPage", "UserRegistration")">Registrare</a></li>
                                  <li><a href="@Url.Action("LogOut", "Login")">Deconectare</a></li>
                                  <li><a href="@Url.Action("MyCabinet", "Account")">Contul meu</a></li>
                                  <!-- Setting Area End Here -->
                             </ul>
                        </div>
                    </div>
                    <!-- Header Top Right Area End Here -->
                </div>
            </div>
        </div>
        <!-- Header Top Area End Here -->
        <!-- Begin Header Middle Area -->
        <div class="header-middle pl-sm-0 pr-sm-0 pl-xs-0 pr-xs-0">
            <div class="container">
                <div class="row">
                    <!-- Begin Header Logo Area -->
                    <div class="col-lg-3">
                        <div class="logo pb-sm-30 pb-xs-30">
                            <img src="~/Content/images/menu/logo/2.png" alt="">
                        </div>
                    </div>
                    <!-- Header Logo Area End Here -->
                    <!-- Begin Header Middle Right Area -->
                    <div class="col-lg-9 pl-0 ml-sm-15 ml-xs-15">
                        <!-- Begin Header Middle Searchbox Area -->
                        <form action="@Url.Action("Search", "SearchBar")" class="hm-searchbox" method="get">
                            <input type="text" name="query" placeholder="Scrie aici ...">
                            <button class="li-btn" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                        <!-- Header Middle Searchbox Area End Here -->
                        <!-- Begin Header Middle Right Area -->
                        <div class="header-middle-right">
                            <ul class="hm-menu">
                                <!-- Begin Header Mini Cart Area -->
                                <li class="hm-minicart">
                                    <a href="@Url.Action("Index", "Order")" class="hm-minicart-trigger">
                                        <span class="item-icon"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("MyOrders", "MyOrder")">My Orders</a>
                                </li>
                                <!-- Header Mini Cart Area End Here -->
                            </ul>
                        </div>
                        <!-- Header Middle Right Area End Here -->
                    </div>
                    <!-- Header Middle Right Area End Here -->
                </div>
            </div>
        </div>
        <!-- Header Middle Area End Here -->
        <!-- Begin Header Bottom Area -->
        <div class="header-bottom header-sticky stick d-none d-lg-block d-xl-block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Begin Header Bottom Menu Area -->
                        <div class="hb-menu">
                            <nav>
                                <ul>
                                    <li><a href="@Url.Action("HomePage", "Home")">Home</a></li="dropdown-holder">
                                    <li class="megamenu-holder">
                                        <a href="">Shop</a>
                                        <ul class="megamenu hb-megamenu">
                                            <li>
                                                <a href="">Jocuri</a>
                                                <ul>
                                                    <li><a href="@Url.Action("NintendoGames", "NintendoGames")">Jocuri Nintendo</a></li>
                                                    <li><a href="@Url.Action("ConsoleGames", "ConsoleGames")">Jocuri Console</a></li>
                                                    <li><a href="@Url.Action("PCGames", "PCGames")">Jocuri PC</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <!-- Header Bottom Menu Area End Here -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Header Bottom Area End Here -->
        <!-- Begin Mobile Menu Area -->
        <div class="mobile-menu-area mobile-menu-area-4 d-lg-none d-xl-none col-12">
            <div class="container">
                <div class="row">
                    <div class="mobile-menu">
                    </div>
                </div>
            </div>
        </div>
        <!-- Mobile Menu Area End Here -->
    </header>
    <!-- Header Area End Here -->
</div>

eUseControl/eUseControl.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>

<html class="no-js" lang="zxx">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>EasyPlay</title>

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900">

    <!-- Favicon -->
    <link href="~/Content/images/favicon.png" rel="icon">

    <!--Vendor CSS Files-->
    <!--Styles.Render("~/bundles/styles/Site/css")-->
    @Styles.Render("~/bundles/styles/jquery-ui/css")
    @Styles.Render("~/bundles/styles/meanmenu/css")
    @Styles.Render("~/bundles/styles/material-design-iconic-font/css")
    @Styles.Render("~/bundles/styles/font-awesome/css")
    @Styles.Render("~/bundles/styles/font-awesome-stars/css")
    @Styles.Render("~/bundles/styles/owl-carousel/css")
    @Styles.Render("~/bundles/styles/slick/css")
    @Styles.Render("~/bundles/styles/animate/css")
    @Styles.Render("~/bundles/styles/venobox/css")
    @Styles.Render("~/bundles/styles/nice-select/css")
    @Styles.Render("~/bundles/styles/magnific-popup/css")
    @Styles.Render("~/bundles/styles/bootstrap/css")
    @Styles.Render("~/bundles/styles/helper/css")


    @if (IsSectionDefined("Styles"))
    {
        @RenderSection("Styles", required: false)
    }

    <!--Main CSS File-->
    @Styles.Render("~/bundles/styles/style/css")
    @Styles.Render("~/bundles/styles/responsive/css")


</head>

<body>

    <div class="body-wrapper">

        <!--Header-->
        <header class="li-header-4">
            @Html.Partial("_Header")
        </header>

        <!--Main Content-->
        <div class="static-top-wrap">
            @RenderBody()
        </div>

        <!--Footer-->
        <div class="footer">
            @Html.Partial("_Footer")
        </div>

        <!--Vendor JS Files-->
        @Scripts.Render("~/bundles/popper/js")
        @Scripts.Render("~/bundles/jquery-3.7.1/js")
        @Scripts.Render("~/bundles/jquery-1.12.4/js")
        @Scripts.Render("~/bundles/modernizr-2.8.3/js")

        <!--Other-->
        @Scripts.Render("~/bundles/jquery-ui/js")
        @Scripts.Render("~/bundles/jquery-validate/js")
        @Scripts.Render("~/bundles/scrollUp/js")
        @Scripts.Render("~/bundles/venobox/js")
        @Scripts.Render("~/bundles/jquery-nice-select/js")
        @Scripts.Render("~/bundles/jquery-barrating/js")
        @Scripts.Render("~/bundles/waypoints/js")
        @Scripts.Render("~/bundles/jquery-counterup/js")
        @Scripts.Render("~/bundles/jquery-countdown/js")
        @Scripts.Render("~/bundles/jquery-mixitup/js")
        @Scripts.Render("~/bundles/imagesloaded-pkgd/js")
        @Scripts.Render("~/bundles/isotope-pkgd/js")
        @Scripts.Render("~/bundles/magnific-popup/js")
        @Scripts.Render("~/bundles/owl-carousel/js")
        @Scripts.Render("~/bundles/slick/js")
        @Scripts.Render("~/bundles/wow/js")
        @Scripts.Render("~/bundles/popper/js")
        <!--Scripts.Render("~/bundles/jquery-1.12.4/js")-->
        <!--Scripts.Render("~/bundles/jquery-3.7.1/js")-->
        <!--Scripts.Render("~/bundles/jquery-3.7.1-min/js")-->
        @Scripts.Render("~/bundles/ajax-mail/js")
        @Scripts.Render("~/bundles/bootstrap/js")
        @Scripts.Render("~/bundles/jquery-meanmenu/js")

        <!-- Template Main JS File -->
        @Scripts.Render("~/bundles/main/js")

        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>